### ISSUE TITLE
Not getting parsed results on command line

### ISSUE THREAD

**Issue by adarshshetty18** [Dheerajmadhukar/karma_v1#2]
I'm just getting the following output on using the tool:
```
Saved 50 results into file ssl_domain_example.com.json.gz

Saved 1 results into file ssl_issuer_example.com.json.gz

Saved 0 results into file org_domain_example.com.json.gz
```
The README shows a parsed output in the command line which I'm not able to see.

**Comment by Dheerajmadhukar** [comment]
It depends on target. 51 IPs found according to your info, then "Karma_v1" will verify each IP with SSL/TLS certificate issuer match RegEx.
