### ISSUE TITLE
Issue on httpx installation...

### ISSUE THREAD

**Issue by sakyb7** [Dheerajmadhukar/karma_v1#4]
Hi,
I'm having an issue while running karma_v1.
i already have insltalled HTTPX on my system but it still have in issue.. ScreenShot below.
![Screenshot from 2021-08-04 20-28-08](https://user-images.githubusercontent.com/42310984/128205218-2d2ebd24-8570-4d9c-8ab6-eb057963fd8c.png)

**Comment by Dheerajmadhukar** [comment]
Its working fine at my end. 


Still you can copy httpx binary to /bin and then check.
